config/routes.rb
Rails.application.routes.draw do
    
  root 'sites#index'
  resources :sites
end

app/models/link.rb
class Link < ActiveRecord::Base

	belongs_to :site
end

app/models/site.rb
class Site < ActiveRecord::Base


	has_many :links, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :find_site, only:[:show, :edit, :update, :destroy]

  def index
  	@sites = Site.all
  end

  def new
  	@site = Site.new
  end

  def create

    url = site_params["address"]
    links_arr = find_links(url)

  	@site = Site.new(site_params)
  	if @site.save
  		redirect_to sites_path, flash: {success: "SITE ADDED, CHECKING LINKS"}
  	else 
  		render :new_site, flash: {alert: "FAILED TO ADD NEW SITE"}
  	end
  end

  def edit
  end

  def update
  	@site.update(site_params)
  	if @site.save
  		redirect_to sites_path, flash: {success: "SITE UPDATED"}
  	else
  		render :edit_site, flash: {alert: "FAILED TO UPDATE SITE"}
  	end
  end

  def show
  end

  def destroy
  	@site.destroy
  	redirect_to sites_path, flash: {alert: "SITE REMOVED"}	
  end

  private
  	def find_site
  		@site = Site.find_by_id(params[:id])	
  	end

  	def site_params
  		params.require(:site).permit(:name, :address)
  	end

    def find_links(url)
      response = RestClient.get url, :user_agent => 'Chrome'
      page = Nokogiri::HTML(response)
      links_array = []
      links = page.css('a')
      links.each do |link|
      href = link.attr('href')
      links_array << href
    end
      links_array
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SidekiqLinkChecker</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="navbar">
  
	
    <nav class="nope">
      <ul>        
        <li><%= link_to "Sites", sites_path  %></li>
         <li><%= link_to "Add New Site", new_site_path  %></li>
        
      </ul>
    </nav>
  </div>

	<div class="buffer"></div>

	<% flash.each do |key, value| %>
	  <% if key == "notice" %>
	    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
	  <% elsif key == "alert" %>
	    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
	  <% elsif key == "info" %>
	    <%= content_tag :div, value, class: "text-center alert alert-info" %>
	  <% else %>
	    <%= content_tag :div, value, class: "text-center alert alert-success" %>
	  <% end %>
	<% end %> 

<%= yield %>

</body>
</html>

app/views/sites/edit.html.erb
<h1>Edit a New Site</h1>

<div class="new-form">
    <% if @site.errors.any? %>
        <% @site.errors.full_messages.each do |error| %>
            <p style="color:red;"> <%= error %> </p>
        <% end %>
    <% end %>

    <%= form_for @site do |f| %>
        <div>
            <%= f.label :search %>
            <%= f.text_field :search, class: "t-field1" %>
        </div>
        <%= f.submit "Search", class: "btn btn-default btn-danger" %>
    <% end %>
</div>

app/views/sites/index.html.erb
<table class="authors-table sortable table table-striped">
	<thead class="author-table-head">
		<tr>
			<th style="text-align:center;">Site Name</th>
			<th style="text-align:center;">Address</th>
			<th style="text-align:center;">Number of Links</th>
			<th style="text-align:center;">Remove Site</th>
			
			
		</tr>
	</thead>
	<tbody>
		<% @sites.each do |site| %>
		<tr>
			<td class="center-me"><%= site.name %></td>
			<td class="center-me"><%= link_to site.address %> </td>
			<td class="center-me"><%= site.links.length %></td>
			<td class="center-me"> <%= button_to 'X', {:controller => :sites, 																									   									 	 :action => "destroy", id: site.id}, 																				 									   class: "btn btn-danger btn-xs",
			 												 									 :method => :delete, data: { confirm: 'Are you sure you want to remove this site?' } %> 
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/sites/new.html.erb
<h1>Check a New Site</h1>

<div class="new-form">
    <% if @site.errors.any? %>
    	<% @site.errors.full_messages.each do |error| %>
    		<p style="color:red;"> <%= error %> </p>
    	<% end %>
    <% end %>
<h4>Enter a site address to check it's links</h4>
    <%= form_for @site do |f| %>
        <div>
            <%= f.label :name %>
            <%= f.text_field :name, class: "t-field1" %>
        </div>
        <div>
            <%= f.label :address %>
            <%= f.text_field :address, class: "t-field1" %>
        </div>
        <%= f.submit "Add Site", class: "btn btn-default btn-danger" %>
    <% end %>
</div>

app/views/sites/show.html.erb
<h1>Sites#show</h1>
<p>Find me in app/views/sites/show.html.erb</p>